---
# this playbook is entry point
- hosts: all
  sudo: True
  roles:
    - role: reiniervdwindt.npm
    
  tasks:
    - name: install babel
      shell: npm install -g babel
    
    - name: install babel-cli
      shell: npm install -g babel-cli
